### ISSUE TITLE
px-chart-controls blocking whole page from loading

### ISSUE THREAD

**Issue by fedechagu** [PredixDev/px-chart#12] opened 2016-04-20 21:54 UTC
We are using this component inside the ui-microapp provided by the hubs team. The code looks like this:

`<link rel="import" href="bower_components/px-chart/px-chart.html"/>`

```
<div class="pxh-card">
  <header class="u-mb flex flex--middle flex--justify">
    <h3 class="caps u-mv0" id="headertext">
      Asset Temperature
    </h3>
  </header>
  <section class="content">
    <px-chart id="timeseries-data">
      <px-chart-series-line
        id="temperature">
      </px-chart-series-line>
    </px-chart>
  </section>
</div>
```

Everything works well locally, we can load all the libraries and see no issues. When we deploy it to CF, it loads the first time prorperly, but when we refresh the page everything stops loading and the page stays blank - no javascript errors. We noticed moment.js is loaded at least 5 times. Only deleting the cache and reloading the page makes the website work again. 

I looked at px-chat.html and started commenting out imports to see if one of the was causing issues. I isolated the issue to the following import:

`<!--<link rel="import" href="px-chart-controls.html"/>-->`

When I comment that one out, everything works fine. I see that there are many things being imported which have other dependencies as well and the all load moment.js. I'm not sure what the issue is inside this dependency but it's definitively a huge blocker for our team - our whole application stops working because of it. Let me know if you need more details.

**Comment by mdwragg** [comment] 2016-04-21 17:14
Hi, thanks for raising the issue (and for taking time to explain it so well). Can you provide a fiddle/jsbin link that exhibits the behaviour please? See this link as an example of how to create one:

http://jsfiddle.net/iamcap/3xyr6ppz/10/

Thanks!

cc/ @nonmetalhail

**Comment by nonmetalhail** [comment] 2016-04-28 23:52
@fedechagu Do you have this issue in Firefox or just Chrome?

**Comment by nonmetalhail** [comment] 2016-04-28 23:52
Also, what happens if you throttle your connection when running locally?

**Comment by nonmetalhail** [comment] 2016-04-29 01:07
@fedechagu So we think we have resolved this problem. It ultimately being caused by px-rangepicker (which gets imported by chart-controls). Please try using the "seed" branch of px-rangepicker and let us know if you encounter this issue with that branch. If not, we will merge it into master.

https://github.com/PredixDev/px-rangepicker/tree/seed

**Comment by fedechagu** [comment] 2016-05-04 23:19
Sorry for the late response I was on vacation. I am using the library in production and installed using bower, so this needs to be integrated into a new version. Could you let me know when there is a new version available?

**Comment by nonmetalhail** [comment] 2016-05-04 23:40
merged. update your bower dependencies.

**Closed by nonmetalhail** 2016-05-04 23:40 UTC
